package gasstationgui.view;

import gasstationgui.controller.FuelController;
import gasstationgui.model.GasStation;
import gasstationgui.model.TableModelFuel;
//import gasstationgui.model.TableModelLog;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Giovani
 */
public class FuelView extends javax.swing.JFrame {
        private final FuelController Fcontroller;
        private final TableModelFuel tableModelFuel;
        //private final TableModelLog tableModelLog;
        private final int index;

    /**
     * Creates new form FuelView
     * @param index
     * @param GStations
     */
    public FuelView(int index, ArrayList<GasStation> GStations) {
        initComponents();
        this.index = index; 
        tableModelFuel = new TableModelFuel(index, GStations);
        tableFuel.setModel(tableModelFuel);
        
        /*tableModelLog = new TableModelLog(tableFuel.getSelectedRow(), tableModelFuel.getFuelArray());
        tablePriceLog.setModel(tableModelLog);*/
              
        Fcontroller = new FuelController(this, tableModelFuel);
    }
    
    // Retorna o index da tabela de Postos que foi selecionado
    public int getGasStationIndex(){
        return index;
    }
    
    // Retorna a tabela do cadastro de combustiveis
    public JTable getTableFuel(){
        return tableFuel;
    }
    
        // Getters do cadastro de combustiveis
    public JTextField getTextTipoComb(){
        return TextTipoComb;
    }
    public JTextField getTextDataColeta(){
        return TextDataColeta;
    }
    public JTextField getTextPreco(){
        return TextPreco;
    }
    
    // Janela de aviso para dado de entrada invalido
    public void showError(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFuelRegister = new javax.swing.JLabel();
        jLabelTipoComb = new javax.swing.JLabel();
        TextTipoComb = new javax.swing.JTextField();
        jLabelDataColet = new javax.swing.JLabel();
        TextDataColeta = new javax.swing.JTextField();
        jLabelPreco = new javax.swing.JLabel();
        TextPreco = new javax.swing.JTextField();
        jButtonInserirComb = new javax.swing.JButton();
        jButtonRemoverComb = new javax.swing.JButton();
        jButtonAlterarComb = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFuel = new javax.swing.JTable();
        jButtonLimpar = new javax.swing.JButton();
        jButtonHistoricoPrecos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelFuelRegister.setText("Fuel Register");

        jLabelTipoComb.setText("Tipo de Combustivel:");

        TextTipoComb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTipoCombActionPerformed(evt);
            }
        });

        jLabelDataColet.setText("Data de coleta do Preço:");

        TextDataColeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDataColetaActionPerformed(evt);
            }
        });

        jLabelPreco.setText("Preço de Venda:");

        TextPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPrecoActionPerformed(evt);
            }
        });

        jButtonInserirComb.setText("Inserir");
        jButtonInserirComb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirCombActionPerformed(evt);
            }
        });

        jButtonRemoverComb.setText("Remover");
        jButtonRemoverComb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverCombActionPerformed(evt);
            }
        });

        jButtonAlterarComb.setText("Alterar Preço/Data");
        jButtonAlterarComb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarCombActionPerformed(evt);
            }
        });

        tableFuel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableFuel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableFuelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableFuel);

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonHistoricoPrecos.setText("Ver Histórico de Preços");
        jButtonHistoricoPrecos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHistoricoPrecosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonHistoricoPrecos))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTipoComb)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelDataColet)
                                                .addComponent(jLabelPreco))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(TextDataColeta)
                                                .addComponent(TextPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(TextTipoComb, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelFuelRegister))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonLimpar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonRemoverComb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonInserirComb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(81, 81, 81)
                        .addComponent(jButtonAlterarComb)
                        .addGap(9, 9, 9)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFuelRegister)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTipoComb)
                            .addComponent(TextTipoComb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDataColet)
                            .addComponent(TextDataColeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPreco)
                            .addComponent(TextPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonInserirComb)
                            .addComponent(jButtonAlterarComb))
                        .addGap(3, 3, 3)
                        .addComponent(jButtonRemoverComb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonHistoricoPrecos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextTipoCombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTipoCombActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextTipoCombActionPerformed

    private void TextDataColetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDataColetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDataColetaActionPerformed

    private void TextPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPrecoActionPerformed

    private void jButtonInserirCombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirCombActionPerformed
        Fcontroller.insertF();
    }//GEN-LAST:event_jButtonInserirCombActionPerformed

    private void jButtonRemoverCombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverCombActionPerformed
        Fcontroller.removeF();
    }//GEN-LAST:event_jButtonRemoverCombActionPerformed

    private void jButtonAlterarCombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarCombActionPerformed
        Fcontroller.updateF();
    }//GEN-LAST:event_jButtonAlterarCombActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        Fcontroller.clear();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void tableFuelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableFuelMouseClicked
        Fcontroller.selectF();
    }//GEN-LAST:event_tableFuelMouseClicked

    private void jButtonHistoricoPrecosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHistoricoPrecosActionPerformed
        if(tableFuel.getSelectedRow() != -1){ // deve existir um combustivel a ser selecionado
            JFrame Log = new LogView(tableFuel.getSelectedRow(), tableModelFuel.getFuelArray());
            Log.setVisible(true);
        }
    }//GEN-LAST:event_jButtonHistoricoPrecosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextDataColeta;
    private javax.swing.JTextField TextPreco;
    private javax.swing.JTextField TextTipoComb;
    private javax.swing.JButton jButtonAlterarComb;
    private javax.swing.JButton jButtonHistoricoPrecos;
    private javax.swing.JButton jButtonInserirComb;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonRemoverComb;
    private javax.swing.JLabel jLabelDataColet;
    private javax.swing.JLabel jLabelFuelRegister;
    private javax.swing.JLabel jLabelPreco;
    private javax.swing.JLabel jLabelTipoComb;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableFuel;
    // End of variables declaration//GEN-END:variables
}
