package gasstationgui.view;

import gasstationgui.model.TableModelGasStation;
import gasstationgui.controller.GasStationController;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Giovani
 */
public class GasStationView extends javax.swing.JFrame {
    private final TableModelGasStation tableModelGasStation;
    private final GasStationController controller;
    private TableRowSorter<TableModel> rowSorter;

    /**
     * Creates new form GasStationView
     */
    public GasStationView() {
        initComponents();
        tableModelGasStation = new TableModelGasStation();
        tableGasStation.setModel(tableModelGasStation); 
        controller = new GasStationController(this, tableModelGasStation);
        
        // Ação do botão Buscar
        this.rowSorter = new TableRowSorter<>(tableGasStation.getModel());
        tableGasStation.setRowSorter(rowSorter);    
        TextBuscar.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = TextBuscar.getText();
                if(text.trim().length() == 0){
                    rowSorter.setRowFilter(null);
                }
                else{
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }
            
            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = TextBuscar.getText();
                if(text.trim().length() == 0){
                    rowSorter.setRowFilter(null);
                }
                else{
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }
            
            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });        
        
    }
    
    // Retorna a tabela do cadastro de postos
    public JTable getTableGasStation() {
        return tableGasStation;
    }
    
    // Abaixo estao o getters dos JTextFields da interface gráfica
    public JTextField getTextCNPJ(){
        return TextCNPJ;
    } 
    public JTextField getTextRazaoSoc(){
        return TextRazaoSoc;
    }  
    public JTextField getTextNomeFantasia(){
        return TextNomeFantasia;
    }
    public JTextField getTextBandeira(){
        return TextBandeira;
    }
    public JTextField getTextEndereco(){
        return TextEndereco;
    }
    public JTextField getTextBairro(){
        return TextBairro;
    }
    public JTextField getTextCEP(){
        return TextCEP;
    }
    public JTextField getTextImagem(){
        return TextImagem;
    }
    public JTextField getTextSearch(){
        return TextBuscar;
    }
    
    public JTextField getTextBuscar(){
        return TextBuscar;
    }
        
    // para mostrar a foto
    public JLabel getLabelImage(){
        return LabelImage;
    }
    
    // Janela de aviso para dado de entrada invalido
    public void showError(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleGasStationRegister = new javax.swing.JLabel();
        jLabelCNPJ = new javax.swing.JLabel();
        jLabelRazao = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelBand = new javax.swing.JLabel();
        jLabelEnd = new javax.swing.JLabel();
        jLabelBairro = new javax.swing.JLabel();
        jLabelCEP = new javax.swing.JLabel();
        TextCNPJ = new javax.swing.JTextField();
        TextNomeFantasia = new javax.swing.JTextField();
        TextRazaoSoc = new javax.swing.JTextField();
        TextBandeira = new javax.swing.JTextField();
        TextEndereco = new javax.swing.JTextField();
        TextCEP = new javax.swing.JTextField();
        TextBairro = new javax.swing.JTextField();
        TextBuscar = new javax.swing.JTextField();
        jButtonLimpar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonRemoverPost = new javax.swing.JButton();
        jButtonInserirPost = new javax.swing.JButton();
        jLabelBuscar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableGasStation = new javax.swing.JTable();
        jLabelPostosCadast = new javax.swing.JLabel();
        jLabelImagem = new javax.swing.JLabel();
        TextImagem = new javax.swing.JTextField();
        LabelImage = new javax.swing.JLabel();
        jButtonVerCombustiveis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitleGasStationRegister.setText("Gas Station Register");

        jLabelCNPJ.setText("CNPJ:");

        jLabelRazao.setText("Razão Social:");

        jLabelNome.setText("Nome Fantasia:");

        jLabelBand.setText("Bandeira:");

        jLabelEnd.setText("Endereço:");

        jLabelBairro.setText("Bairro:");

        jLabelCEP.setText("CEP:");

        TextCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCNPJActionPerformed(evt);
            }
        });

        TextRazaoSoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextRazaoSocActionPerformed(evt);
            }
        });

        TextBandeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextBandeiraActionPerformed(evt);
            }
        });

        TextEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextEnderecoActionPerformed(evt);
            }
        });

        TextBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextBuscarActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar Posto");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonRemoverPost.setText("Remover Posto");
        jButtonRemoverPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverPostActionPerformed(evt);
            }
        });

        jButtonInserirPost.setText("Inserir Posto");
        jButtonInserirPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirPostActionPerformed(evt);
            }
        });

        jLabelBuscar.setText("Buscar por Bairro:");

        tableGasStation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableGasStation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableGasStationMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableGasStation);

        jLabelPostosCadast.setText("Postos Cadastrados");

        jLabelImagem.setText("Imagem:");

        LabelImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonVerCombustiveis.setText("Ver Combustiveis Cadastrados");
        jButtonVerCombustiveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerCombustiveisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TitleGasStationRegister)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelBuscar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabelCEP)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(TextCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabelEnd)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(TextEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabelNome)
                                                    .addComponent(jLabelCNPJ))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(TextCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(TextNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelBand)
                                            .addComponent(jLabelImagem)
                                            .addComponent(jLabelBairro)
                                            .addComponent(jLabelRazao))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextRazaoSoc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextBandeira, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonInserirPost)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonRemoverPost)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonLimpar))
                                    .addComponent(TextBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPostosCadast)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVerCombustiveis)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(TitleGasStationRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextRazaoSoc)
                            .addComponent(jLabelRazao)
                            .addComponent(jLabelCNPJ))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TextNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelBand)
                                    .addComponent(TextBandeira, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNome))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TextEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelEnd)
                                    .addComponent(jLabelBairro)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(TextBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCEP)
                            .addComponent(TextCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelImagem)
                            .addComponent(TextImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonInserirPost)
                            .addComponent(jButtonAlterar)
                            .addComponent(jButtonRemoverPost)
                            .addComponent(jButtonLimpar))
                        .addGap(64, 64, 64)
                        .addComponent(jLabelBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LabelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPostosCadast)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonVerCombustiveis)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCNPJActionPerformed

    private void TextEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEnderecoActionPerformed

    private void TextBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextBuscarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        controller.clear();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void TextRazaoSocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextRazaoSocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextRazaoSocActionPerformed

    private void jButtonInserirPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirPostActionPerformed
        controller.insert();
    }//GEN-LAST:event_jButtonInserirPostActionPerformed

    private void jButtonRemoverPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverPostActionPerformed
        controller.remove();
    }//GEN-LAST:event_jButtonRemoverPostActionPerformed

    private void TextBandeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextBandeiraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextBandeiraActionPerformed

    private void tableGasStationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableGasStationMouseClicked
        controller.select();
    }//GEN-LAST:event_tableGasStationMouseClicked

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        controller.update();
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonVerCombustiveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerCombustiveisActionPerformed
        if(tableGasStation.getSelectedRow() != -1){       // deve existir um posto a ser selecionado
            int viewRow = tableGasStation.getSelectedRow();
            JFrame Fuel = new FuelView(tableGasStation.convertRowIndexToModel(viewRow), tableModelGasStation.getGasStationArray());
            Fuel.setVisible(true);
        }
    }//GEN-LAST:event_jButtonVerCombustiveisActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImage;
    private javax.swing.JTextField TextBairro;
    private javax.swing.JTextField TextBandeira;
    private javax.swing.JTextField TextBuscar;
    private javax.swing.JTextField TextCEP;
    private javax.swing.JTextField TextCNPJ;
    private javax.swing.JTextField TextEndereco;
    private javax.swing.JTextField TextImagem;
    private javax.swing.JTextField TextNomeFantasia;
    private javax.swing.JTextField TextRazaoSoc;
    private javax.swing.JLabel TitleGasStationRegister;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonInserirPost;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonRemoverPost;
    private javax.swing.JButton jButtonVerCombustiveis;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelBand;
    private javax.swing.JLabel jLabelBuscar;
    private javax.swing.JLabel jLabelCEP;
    private javax.swing.JLabel jLabelCNPJ;
    private javax.swing.JLabel jLabelEnd;
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPostosCadast;
    private javax.swing.JLabel jLabelRazao;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableGasStation;
    // End of variables declaration//GEN-END:variables
}
