package gasstationgui.view;

import gasstationgui.model.TableModelGasStation;
import gasstationgui.controller.GasStationController;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Giovani
 */
public class GasStationView extends javax.swing.JFrame {
    private TableModelGasStation tableModelGasStation;
    private GasStationController controller;

    /**
     * Creates new form GasStationView
     */
    public GasStationView() {
        initComponents();
        tableModelGasStation = new TableModelGasStation();
        tableGasStation.setModel(tableModelGasStation);
        controller = new GasStationController(this, tableModelGasStation);
    }
    
    // Retorna a tabela do cadastro de postos
    public JTable getTableGasStation() {
        return tableGasStation;
    }
    
    // Abaixo estao o getters dos JTextFields da interface gráfica
    public JTextField getTextCNPJ(){
        return TextCNPJ;
    } 
    public JTextField getTextRazaoSoc(){
        return TextRazaoSoc;
    }  
    public JTextField getTextNomeFantasia(){
        return TextNomeFantasia;
    }
    public JTextField getTextBandeira(){
        return TextBandeira;
    }
    public JTextField getTextEndereco(){
        return TextEndereco;
    }
    public JTextField getTextBairro(){
        return TextBairro;
    }
    public JTextField getTextCEP(){
        return TextCEP;
    }
    public JTextField getTextImagem(){
        return TextImagem;
    }
    // para mostrar a foto
    public JLabel getLabelImage(){
        return LabelImage;
    }
    
    // Janela de aviso para dado de entrada invalido
    public void showError(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TitleGasStationRegister = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelRazao = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelBand = new javax.swing.JLabel();
        jLabelEnd = new javax.swing.JLabel();
        jLabelBairro = new javax.swing.JLabel();
        jLabelCEP = new javax.swing.JLabel();
        TextCNPJ = new javax.swing.JTextField();
        TextNomeFantasia = new javax.swing.JTextField();
        TextRazaoSoc = new javax.swing.JTextField();
        TextBandeira = new javax.swing.JTextField();
        TextEndereco = new javax.swing.JTextField();
        TextCEP = new javax.swing.JTextField();
        TextBairro = new javax.swing.JTextField();
        jLabelFuelRegister = new javax.swing.JLabel();
        jLabelTipoComb = new javax.swing.JLabel();
        jLabelDataColet = new javax.swing.JLabel();
        jLabelPreco = new javax.swing.JLabel();
        TextBuscar = new javax.swing.JTextField();
        TextDataColeta = new javax.swing.JTextField();
        TextPrecoVenda = new javax.swing.JTextField();
        jButtonLimpar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonRemoverPost = new javax.swing.JButton();
        jButtonInserirPost = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        TextTipoComb = new javax.swing.JTextField();
        jLabelBuscar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableGasStation = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablelHistoricoPrecos = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablelFuel = new javax.swing.JTable();
        jButtonInserirComb = new javax.swing.JButton();
        jButtonRemoverComb = new javax.swing.JButton();
        jLabelPostosCadast = new javax.swing.JLabel();
        jLabelCombCadastrados = new javax.swing.JLabel();
        jLabelHistPrecos = new javax.swing.JLabel();
        jLabelImagem = new javax.swing.JLabel();
        TextImagem = new javax.swing.JTextField();
        LabelImage = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitleGasStationRegister.setText("Gas Station Register");

        jLabel1.setText("CNPJ:");

        jLabelRazao.setText("Razão Social:");

        jLabelNome.setText("Nome Fantasia:");

        jLabelBand.setText("Bandeira:");

        jLabelEnd.setText("Endereço:");

        jLabelBairro.setText("Bairro:");

        jLabelCEP.setText("CEP:");

        TextCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCNPJActionPerformed(evt);
            }
        });

        TextRazaoSoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextRazaoSocActionPerformed(evt);
            }
        });

        TextBandeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextBandeiraActionPerformed(evt);
            }
        });

        TextEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextEnderecoActionPerformed(evt);
            }
        });

        jLabelFuelRegister.setText("Fuel Register");

        jLabelTipoComb.setText("Tipo de Combustivel:");

        jLabelDataColet.setText("Data de coleta do Preço:");

        jLabelPreco.setText("Preço de Venda:");

        TextBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextBuscarActionPerformed(evt);
            }
        });

        TextDataColeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDataColetaActionPerformed(evt);
            }
        });

        TextPrecoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPrecoVendaActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonRemoverPost.setText("Remover Posto");
        jButtonRemoverPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverPostActionPerformed(evt);
            }
        });

        jButtonInserirPost.setText("Inserir Posto");
        jButtonInserirPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirPostActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        TextTipoComb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTipoCombActionPerformed(evt);
            }
        });

        jLabelBuscar.setText("Buscar por Bairro:");

        tableGasStation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableGasStation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableGasStationMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableGasStation);

        tablelHistoricoPrecos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tablelHistoricoPrecos);

        tablelFuel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tablelFuel);

        jButtonInserirComb.setText("Inserir Combustível");

        jButtonRemoverComb.setText("Remover Combustível");

        jLabelPostosCadast.setText("Postos Cadastrados");

        jLabelCombCadastrados.setText("Combustíveis Cadastrados");

        jLabelHistPrecos.setText("Histórico de Preços");

        jLabelImagem.setText("Imagem:");

        LabelImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButtonRemoverComb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonInserirComb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabelBuscar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextBuscar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonBuscar)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(35, 35, 35)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPostosCadast)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelCombCadastrados))
                                        .addGap(52, 52, 52)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelHistPrecos)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(117, 117, 117))
                            .addComponent(jScrollPane2)))
                    .addComponent(TitleGasStationRegister)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TextCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelCEP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TextCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelEnd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TextEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelNome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TextNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelBand)
                                            .addComponent(jLabelImagem))
                                        .addGap(22, 22, 22))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelRazao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextRazaoSoc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextBandeira, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTipoComb)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelDataColet)
                                                .addComponent(jLabelPreco))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(TextDataColeta)
                                                .addComponent(TextPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(TextTipoComb, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelBairro)
                                    .addComponent(jButtonRemoverPost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonInserirPost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelFuelRegister))
                        .addGap(18, 18, 18)
                        .addComponent(LabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(TitleGasStationRegister)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TextRazaoSoc)
                                    .addComponent(jLabelRazao))
                                .addGap(11, 11, 11))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TextCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TextNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelBand)
                                    .addComponent(TextBandeira, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNome))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TextEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelEnd)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelBairro)
                                    .addComponent(TextBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCEP)
                            .addComponent(TextCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelImagem)
                            .addComponent(TextImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelFuelRegister)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTipoComb)
                            .addComponent(TextTipoComb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonInserirPost)
                            .addComponent(jButtonLimpar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonRemoverPost)
                                .addComponent(jButtonAlterar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelDataColet)
                                .addComponent(TextDataColeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPreco)
                            .addComponent(TextPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(LabelImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPostosCadast)
                    .addComponent(jButtonInserirComb))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonRemoverComb)
                        .addGap(40, 40, 40)
                        .addComponent(jLabelBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelHistPrecos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCombCadastrados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCNPJActionPerformed

    private void TextEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEnderecoActionPerformed

    private void TextBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextBuscarActionPerformed

    private void TextDataColetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDataColetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDataColetaActionPerformed

    private void TextPrecoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPrecoVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPrecoVendaActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        controller.clear();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void TextTipoCombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTipoCombActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextTipoCombActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void TextRazaoSocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextRazaoSocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextRazaoSocActionPerformed

    private void jButtonInserirPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirPostActionPerformed
        controller.insert();
    }//GEN-LAST:event_jButtonInserirPostActionPerformed

    private void jButtonRemoverPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverPostActionPerformed
        controller.remove();
    }//GEN-LAST:event_jButtonRemoverPostActionPerformed

    private void TextBandeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextBandeiraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextBandeiraActionPerformed

    private void tableGasStationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableGasStationMouseClicked
        controller.select();
    }//GEN-LAST:event_tableGasStationMouseClicked

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        controller.update();
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImage;
    private javax.swing.JTextField TextBairro;
    private javax.swing.JTextField TextBandeira;
    private javax.swing.JTextField TextBuscar;
    private javax.swing.JTextField TextCEP;
    private javax.swing.JTextField TextCNPJ;
    private javax.swing.JTextField TextDataColeta;
    private javax.swing.JTextField TextEndereco;
    private javax.swing.JTextField TextImagem;
    private javax.swing.JTextField TextNomeFantasia;
    private javax.swing.JTextField TextPrecoVenda;
    private javax.swing.JTextField TextRazaoSoc;
    private javax.swing.JTextField TextTipoComb;
    private javax.swing.JLabel TitleGasStationRegister;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonInserirComb;
    private javax.swing.JButton jButtonInserirPost;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonRemoverComb;
    private javax.swing.JButton jButtonRemoverPost;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelBand;
    private javax.swing.JLabel jLabelBuscar;
    private javax.swing.JLabel jLabelCEP;
    private javax.swing.JLabel jLabelCombCadastrados;
    private javax.swing.JLabel jLabelDataColet;
    private javax.swing.JLabel jLabelEnd;
    private javax.swing.JLabel jLabelFuelRegister;
    private javax.swing.JLabel jLabelHistPrecos;
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPostosCadast;
    private javax.swing.JLabel jLabelPreco;
    private javax.swing.JLabel jLabelRazao;
    private javax.swing.JLabel jLabelTipoComb;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tableGasStation;
    private javax.swing.JTable tablelFuel;
    private javax.swing.JTable tablelHistoricoPrecos;
    // End of variables declaration//GEN-END:variables
}
